AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Monitoring Stack: CloudWatch Alarms for Lambda errors and DLQ messages.'

Parameters:
  AppStackName:
    Type: String
    Description: "Name of the application stack (e.g., my-app-application)."
  AlarmEmail:
    Type: String
    Description: "Email to send alarm notifications to."

Resources:
  # SNS Топик, куда будут падать все алерты
  AlarmSnsTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - Endpoint: !Ref AlarmEmail
          Protocol: "email"

  # Аларм на ошибки лямбды
  LambdaErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: "Alarm if the Lambda function has errors"
      Namespace: "AWS/Lambda"
      MetricName: "Errors"
      Dimensions:
        - Name: "FunctionName"
          Value: !ImportValue { Fn::Sub: "${AppStackName}-FunctionName" }
      Statistic: "Sum"
      Period: 60
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: "GreaterThanOrEqualToThreshold"
      AlarmActions: [ !Ref AlarmSnsTopic ]

  # САМЫЙ ВАЖНЫЙ АЛАРМ: если в DLQ появилось хоть одно сообщение
  DLQNotEmptyAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: "Alarm if the DLQ is not empty"
      Namespace: "AWS/SQS"
      MetricName: "ApproximateNumberOfMessagesVisible"
      Dimensions:
        - Name: "QueueName"
          Value: !ImportValue
            Fn::Sub: "${AppStackName}-ImageEventsDLQName"
      Statistic: "Sum"
      Period: 60
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: "GreaterThanOrEqualToThreshold"
      AlarmActions: [ !Ref AlarmSnsTopic ]
