version = 0.1

[dev.deploy.parameters]
stack_name = "my-app-application"
resolve_s3 = true
s3_prefix = "my-app-application"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "NetworkStackName=\"my-app-network\" StorageStackName=\"my-app-storage\""
image_repositories = []

[dev.global.parameters]
region = "eu-central-1"

[default.deploy.parameters]
stack_name = "my-app-application"
resolve_s3 = true
s3_prefix = "my-app-application"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "NetworkStackName=\"my-app-network\" StorageStackName=\"my-app-storage\""
image_repositories = []

[default.global.parameters]
region = "eu-central-1"
